repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: detect-aws-credentials
    -   id: detect-private-key
-   repo: git@github.com:Yelp/detect-secrets
    rev: v0.13.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.gds/.secrets.baseline']
        exclude: .*/tests/.*
